apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetorch-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubetorch-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetorch-proxy
  template:
    metadata:
      labels:
        app: kubetorch-proxy
      annotations:
        chart-version: "{{ .Chart.Version }}"
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginxProxy.image.repository }}:{{ .Values.nginxProxy.image.tag }}"
          imagePullPolicy: {{ .Values.nginxProxy.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting nginx with static config"
              cat /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
              nginx -g 'daemon off;'
          ports:
            - containerPort: 8080
            - containerPort: 8873
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf.template
              subPath: nginx.conf
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: nginx-config
          configMap:
            name: kubetorch-proxy-nginx-config-template
