apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetorch-grafana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetorch-grafana
  template:
    metadata:
      labels:
        app: kubetorch-grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.3.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kubetorch-grafana
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kubetorch-grafana
  ports:
    - port: 3000
      targetPort: 3000
