name: Setup Release Testing

description: Reusable steps for prepping release testing

inputs:
  DEV_AWS_ACCESS_KEY:
    description: 'AWS Access Key ID'
    required: false
  DEV_AWS_SECRET_KEY:
    description: 'AWS Secret Access Key'
    required: false
  GCP_SERVICE_ACCOUNT_KEY:
    description: 'GCP Service Account Key'
    required: false
  GCP_PROJECT_ID:
    description: 'GCP Project ID'
    required: false
  KUBECONFIG:
    description: 'Kubeconfig'
    required: false
  TEST_TOKEN:
    description: 'Test Token'
    required: true
  TEST_USERNAME:
    description: 'Test Username'
    required: true
  API_SERVER_URL:
    description: 'API Server URL'
    required: true

runs:
  using: composite
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Configure & Authenticate to AWS
      run: |
        aws configure set aws_access_key_id ${{ inputs.DEV_AWS_ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ inputs.DEV_AWS_SECRET_KEY }}
        aws configure set default.region us-east-1
      shell: bash

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ inputs.GCP_PROJECT_ID }}

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ inputs.GCP_PROJECT_ID }}
        service_account_key: ${{ inputs.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Setup Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ inputs.KUBECONFIG }}" > $HOME/.kube/config
        sudo apt-get update
        sudo apt-get install -y socat
      shell: bash

    - name: Install & check skypilot configuration
      run: |
        python -m pip install --upgrade pip
        pip install skypilot[aws,gcp,kubernetes]
        sky check
        sky status
      shell: bash

    - name: Install python packages & dependencies
      run: |
        pip install runhouse[aws,gcp,kubernetes]
        pip install -r tests/requirements.txt scipy pyarrow
      shell: bash

    - name: Setup Runhouse
      uses: ./.github/workflows/setup_runhouse

    - name: Setup ~/.rh/config.yaml
      uses: ./.github/workflows/setup_rh_config
      with:
        username: ${{ inputs.TEST_USERNAME }}
        token: ${{ inputs.TEST_TOKEN }}
        api_server_url: ${{ inputs.API_SERVER_URL }}
