LOCALHOST: str = "127.0.0.1"
DEFAULT_THANOS_PORT = 10902
DEFAULT_KUBECONFIG_PATH = "~/.kube/config"
MAX_PORT_TRIES = 10

# CLI constants
DOUBLE_SPACE_UNICODE = "\u00A0\u00A0"
BULLET_UNICODE = "\u2022"
DEFAULT_TAIL_LENGTH = 100  # log tail length

MAX_USERNAME_LENGTH = 16
MAX_K8S_NAME_LENGTH = 63

CPU_RATE = 0.01
GPU_RATE = 0.05

KT_MOUNT_FOLDER = "ktfs"
DEFAULT_VOLUME_ACCESS_MODE = "ReadWriteMany"
