LOCALHOST: str = "127.0.0.1"
DEFAULT_KUBECONFIG_PATH = "~/.kube/config"
MAX_PORT_TRIES = 10

# CLI constants
BULLET_UNICODE = "\u2022"

MAX_USERNAME_LENGTH = 16

KT_MOUNT_FOLDER = "ktfs"
DEFAULT_VOLUME_ACCESS_MODE = "ReadWriteMany"

DEFAULT_TAIL_LENGTH = 100  # log tail length
