apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  annotations: {{ annotations | tojson }}
  labels: {{ labels | tojson }}
spec:
  {% if distributed %}
  clusterIP: None  # Headless service for distributed pod discovery
  {% else %}
  sessionAffinity: ClientIP  # Ensure requests from same client go to same pod
  {% endif %}
  selector:
    kubetorch.com/service: {{ deployment_name }}
    kubetorch.com/module: {{ module_name }}  # Only deployment pods have this set, so allows us to exclude the jump pod
  ports:
    - name: http
      port: 80
      targetPort: {{ server_port }}
      protocol: TCP
