{{- if .Values.ephemeralLogStorage.enabled }}
{{- $allNamespaces := .Values.kubetorchConfig.deployment_namespaces | default list }}
{{- if not (has .Release.Namespace $allNamespaces) }}
  {{- $allNamespaces = append $allNamespaces .Release.Namespace }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Release.Namespace }}
data:
  relay: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    receivers:
      filelog:
        include:
        {{- range $allNamespaces }}
          - /var/log/pods/{{ . }}_*/*/*.log
        {{- end }}
        exclude:
          - /var/log/pods/*/otel-collector/*.log
          - /var/log/pods/*/opentelemetry-collector/*.log
        start_at: end
        include_file_path: true
        include_file_name: false
        operators:
          - type: container
            id: container-parser
      k8s_events:
        namespaces:
        {{- range $allNamespaces }}
          - {{ . }}
        {{- end }}
    processors:
      batch: {}
      k8sattributes:
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.container.name
    exporters:
      otlphttp/logs:
        endpoint: "http://loki-gateway.{{ .Release.Namespace }}.svc.cluster.local:3100/otlp"
        tls:
          insecure: true
    service:
      extensions: [health_check]
      telemetry:
        logs:
          level: warn
      pipelines:
        logs:
          receivers: [filelog, k8s_events]
          processors: [k8sattributes, batch]
          exporters: [otlphttp/logs]
{{- end }}
