name: All tests with level "unit"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python packages & dependencies
        run:
          pip install runhouse pytest httpx pytest_asyncio

      - name: Run all unit tests
        run: pytest -v --level unit
