name: Docs

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install kubetorch
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv pip install --system -e ./python_client
        shell: bash

      - name: Install docs requirements
        run: pip install -r python_client/kubetorch/docs/requirements.txt

      - name: Build docs
        run: cd python_client/kubetorch/docs && make html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: python_client/docs/_build/html
