name: pytest -v --level local -k "secrettest"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  secret-tests-logged-in-level-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Runhouse
        uses: ./.github/workflows/setup_runhouse

      - name: Setup ~/.rh/config.yaml
        uses: ./.github/workflows/setup_rh_config
        with:
          username: ${{ secrets.CI_ACCOUNT_USERNAME }}
          token: ${{ secrets.CI_ACCOUNT_TOKEN }}

      - name: pytest -v --level local -k "secrettest"
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        run: pytest -v --level local -k "secrettest"
        timeout-minutes: 60
