name: Release Kubetorch in GHCR

on:
  workflow_dispatch:

jobs:
  release-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Package Helm chart
        run: |
          cd charts/kubetorch
          helm dependency update .
          helm package . --destination ../../..  # outputs kubetorch-<ver>.tgz in repo root

      - name: Extract Helm chart version
        id: get_version
        run: |
          VERSION=$(yq -r '.version' charts/kubetorch/Chart.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: |
          helm registry login ghcr.io --username run-house --password-stdin

      - name: Push chart to GHCR
        run: |
          CHART_TGZ=$(ls kubetorch-*.tgz)
          helm push "$CHART_TGZ" oci://ghcr.io/run-house/charts

      - name: Post to Runhouse Slack channel
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          slack-message: |
            [*kubetorch*] Updated Helm chart in GHCR with version *v${{ steps.get_version.outputs.version }}* 🚀
            Run by: *${{ github.actor }}*
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
