name: sagemaker-tests

on: workflow_dispatch

jobs:
  sagemaker-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure aws credentials
        run: |
          aws sts assume-role --role-arn ${{ secrets.AWS_ROLE_ARN }} --role-session-name "GitHubAction" > assumed-role.json
          export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId assumed-role.json)
          export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey assumed-role.json)
          export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken assumed-role.json)

      - name: Install python packages & dependencies
        run: |
          pip install runhouse[sagemaker]
          pip install tests/requirements.txt

      - name: Run all sagemaker tests
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        run: pytest tests/test_resources/test_clusters/test_sagemaker_cluster/test_sagemaker.py --ignore-filters

      - name: Teardown all SageMaker clusters
        run: |
          aws sagemaker stop-training-job --training-job-name "rh-sagemaker"
          aws sagemaker stop-training-job --training-job-name "rh-sagemaker-2"
